name: Build and Push Docker Image

# Name each workflow run with who's doing what to what branch
run-name: Build ${{ github.event_name }} on ${{ github.ref_name }} by @${{ github.actor }}

on:
  # Run on pushing to any branch
  push:
  # Run on a pull request to any branch
  pull_request:

jobs:
  docker-build-and-push:
    name: Build Docker image and push to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Docker tagging
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          # Docker image tags:
          #   sha:    Unique git commit hash applied to every built image
          #   branch: Branch name being pushed to
          #           (branch tag will always point to latest build from that branch)
          #   latest: If pushing to default (master) branch, tag image as latest
          #           (pulling image without specifying a tag will default to latest)
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Set up a Docker build environment
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Docker image and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
